---

- name: Deploy OliveTin default config file
  ansible.builtin.template:
    src: olivetin.config.yaml.j2
    dest: "{{ olivetin_config_file }}"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set
  notify:
    - Restart OliveTin
  when: olivetin_custom_config_data is undefined

- name: Deploy OliveTin base config file
  ansible.builtin.template:
    src: olivetin_blank.config.yaml.j2
    dest: "{{ olivetin_config_file }}"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set
  notify:
    - Restart OliveTin
  when: olivetin_custom_config_data is defined

- name: Deploy OliveTin custom config file
  ansible.builtin.blockinfile:
    path: "{{ olivetin_config_file }}"
    create: false
    state: present
    insertafter: "after:"
    mode: "0700"
    block: | 
      {{ olivetin_custom_config_data }}
  notify:
    - Restart OliveTin
  when: olivetin_custom_config_data is defined

