---
- name: Install chrony if it's missing
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Add the PTP KVM Module
  community.general.modprobe:
    name: ptp_kvm
    state: present

- name: Add ptp_kvm to the module to be loaded
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/ptp_kvm.conf
    regexp: 'ptp_kvm'
    line: ptp_kvm

- name: Fix Chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set
