---
- name: Template out .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ authentik_base_directory }}/.env"
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set
    owner: "{{ authentik_service_user }}"
    group: "{{ authentik_service_user }}"

- name: Template out docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ authentik_base_directory }}/docker-compose.yml"
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set
    owner: "{{ authentik_service_user }}"
    group: "{{ authentik_service_user }}"

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ authentik_base_directory }}"
    state: present

# Make symbolic links between StepCA certs and Authentik Certs
- name: Make Symbolic Links between actual certs and Authentik cert location
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    owner: "{{ authentik_service_user }}"
    group: "{{ authentik_service_user }}"
    state: link
  loop:
    - {source: "{{ smallstep_web_certificate_path }}", destination: "{{ authentik_web_certificate_path }}"}
    - {source: "{{ smallstep_web_key_path }}", destination: "{{ authentik_web_key_path }}"}
    - {source: "{{ smallstep_ldap_certificate_path }}", destination: "{{ authentik_ldap_certificate_path }}"}
    - {source: "{{ smallstep_ldap_key_path }}", destination: "{{ authentik_ldap_key_path }}"}
