---


- name: Link certificate to Authentik Cert directory
  file:
    src: /file/to/link/to
    dest: /path/to/symlink
    owner: foo
    group: foo
    state: link

- name: Ensure cert-renewer-web@docker.timer is started
  ansible.builtin.service:
    name: "{{ authentik_cert_timer }}"
    state: started
    enabled: true


# Make Web Certificate
# Make LDAP Certificate

# Set Web certificate
