---

- name: Add Universe Repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
    validate_certs: true
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"

- name: Install Dependency packages
  package:
    name:
      - acl
      - sudo
      - python3-pexpect
      - build-essential
      - python3-pip
      - python3-dev
      - python3-lxml
      - libssl-dev
      - python3-dbus
      - python3-augeas
      - python3-apt
      - ntpdate
      # - python
      # - python-lxml
      # - python-gevent
      # - python-gevent-socketio
      # - python-psutil
      # - python-reconfigure
      # - python-passlib
      # - python-requests
      # - python-dbus
      # - python-catcher
      # - python-exconsole
      # - python-daemon
      # - python-imaging
      # - python-ldap
    state: present
