---
- name: Install Ajenti
  ansible.builtin.pip:
    state: latest
    name:
      - package_name
      - ajenti-panel
      - ajenti.plugin.ace
      - ajenti.plugin.augeas
      - ajenti.plugin.auth-users
      - ajenti.plugin.core
      - ajenti.plugin.dashboard
      - ajenti.plugin.datetime
      - ajenti.plugin.filemanager
      - ajenti.plugin.filesystem
      - ajenti.plugin.network
      - ajenti.plugin.notepad
      - ajenti.plugin.packages
      - ajenti.plugin.passwd
      - ajenti.plugin.plugins
      - ajenti.plugin.power
      - ajenti.plugin.services
      - ajenti.plugin.settings
      - ajenti.plugin.terminal

- name: Install Ajenti Service
  ansible.builtin.template:
    src: ajenti.service.j2
    dest: "/etc/systemd/system/ajenti.service"
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set

- name: Ensure ajenti is restarted
  ansible.builtin.service:
    name: "{{ ajenti_name }}"
    state: restarted
    enabled: true
