---
# Items for Default Installation
authentik_service_user: authentik_user
authentik_base_directory: /opt/authentik
authentik_pgpass: "{{ lookup('community.general.random_string', length=40, special=false) }}"
authentik_secret_key: "{{ lookup('community.general.random_string', length=50, special=false) }}"

# Items for SMTP
authentik_smtp_host: "smtp.gmail.com"
authentik_smtp_port: "587"
authentik_smtp_ssl: "false"
authentik_smtp_tls: "true"
authentik_smtp_username: "my_user@gmail.com"
authentik_smtp_password: "my_password"
authentik_admin_user_email: "authentik_admin@example.com"

# Items for provisioning the Service
my_app_inital_cert_location: "/etc/step-ca"
my_app_dependent_service: "docker"
my_app_external_domain: "auth.tucc.io"
my_app_certificate_path: "{{ authentik_base_directory }}/certificate.crt"
my_app_key_path: "{{ authentik_base_directory }}/certificate.key"
my_app_cert_renewer_path: "/etc/systemd/system/cert-renewer@{{ my_app_dependent_service }}.service.d"
my_app_cert_timer: cert-renewer@{{ my_app_dependent_service }}.timer""
