---
# tasks file for db_mysql
- name: Install dependencies
  package:
    name: 
      - mariadb-server
      - python3-pymysql

- name: Create a database
  community.mysql.mysql_db:
    name: "{{ app_name }}_db"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    encoding: "utf8mb4"
    collation: "utf8mb4_unicode_ci"
    check_implicit_admin: yes

- name: Create database user with all database privileges
  community.mysql.mysql_user:
    name: "{{ app_name }}_dbuser"
    password: "{{ app_user_pw }}"
    priv: "{{ app_name }}_db.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present