galaxy_info:
  role_name: cd_bitwarden
  namespace: irontooch
  author: IronTooch
  description: Meant to install Bitwarden on a bare-metal server
  license: GPL-3.0-only
  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
      - focal

  galaxy_tags: []

dependencies: []
