---
# tasks file for cd_samba
    - name: Update Apt Cache
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Grab dependency file
      get_url:
        url: 'https://git.samba.org/?p=samba.git;a=blob_plain;f=bootstrap/generated-dists/ubuntu1804/bootstrap.sh;hb=v4-14-test'
        dest: '/tmp/samba_bootstrap.sh'
        mode: '0777'
    - name: Get current user
      shell:
        cmd: 'whoami'
      register: result
    - name: Print Current User
      debug:
        msg: "{{ result }}"
    - name: Install dependencies
      package:
        name:
          - acl
          - attr
          - autoconf
          - bind9utils
          - bison
          - build-essential
          - debhelper
          - dnsutils
          - docbook-xml
          - docbook-xsl
          - flex
          - gdb
          - krb5-user
          - libacl1-dev
          - libaio-dev
          - libarchive-dev
          - libattr1-dev
          - libblkid-dev
          - libbsd-dev
          - libcap-dev
          - libcups2-dev
          - libgnutls28-dev
          - libgpgme-dev
          - libjansson-dev
          - libjson-perl
          - libldap2-dev
          - liblmdb-dev
          - libncurses5-dev
          - libpam0g-dev
          - libparse-yapp-perl
          - libpopt-dev
          - libreadline-dev
          - lmdb-utils
          - nettle-dev
          - perl
          - perl-modules
          - pkg-config
          - python-all-dev
          - python-crypto
          - python-dbg
          - python-dev
          - python-dnspython
          - python-gpg
          - python-markdown
          - python3-dev
          - python3-dnspython
          - python3-gpg
          - python3-markdown
          - samba
          - smbclient
          - winbind
          - xsltproc
          - zlib1g-dev
    - name: Remove SMB file
      file: 
        path: /etc/samba/smb.conf
        state: absent
    - name: Shut off services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - smbd
        - nmbd
        - winbind
        - systemd-resolved
    - name: Mask Services
      shell: 
        cmd: "systemctl mask {{ item }}"
      loop:
        - smbd
        - nmbd
        - winbind
        - systemd-resolved
    - name: Unmask Samba AD
      shell:
        cmd: "systemctl unmask samba-ad-dc"
    - name: Enable Samba AD DC
      service:
        name: samba-ad-dc
        enabled: true
    - name: Template Samba Provisioning Script
      template: 
        src: samba_provision.sh.j2
        dest: /tmp/samba_provision.sh
    - name: Run Samba Provisioning Tool
      shell:
        cmd: "bash /tmp/samba_provision.sh"
    - name: Remove SMB file
      file: 
        path: /etc/krb5.conf
        state: absent
    - name: Copy kerberos file
      copy:
        src: /var/lib/samba/private/krb5.conf
        dest: /etc/krb5.conf
        remote_src: yes
    - name: Template out smb.conf file
      template: 
        src: smb.conf.j2
        dest: /etc/samba/smb.conf
    - name: Enable Samba AD DC
      service:
        name: samba-ad-dc
        state: restarted
    - name: Reboot server
      reboot:
    - name: Add Bind User
      shell: "samba-tool user create srv_LdapBindUser '"{{ bind_user_password }}"'"