---
# defaults file for db_postgresql
app_name: "exampleapp"
default_postgres_system_user: "postgres"
postgres_db: "{{ app_name }}_db"
postgres_dbuser: "{{ app_name }}_dbuser"
postgres_dbpassword: ""
pga_restricted_cidr: "0/0"  # No restrictions
hba_conf_location: "/etc/postgresql/{{ postgres_major_ver }}/main/pg_hba.conf"
postgres_pass_location: "/etc/postgresql/{{ postgres_major_ver }}/postgres_db_pass.txt"
