---
# defaults file for cd_bitwarden
service_user: bitwarden_user
bitwarden_sh_url: "https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh"
external_domain: "bitwarden.example.com"
installation_id: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
installation_key: "aaaaaaaaaaaaaaaaaaaa"
bitwarden_dir: "/opt/bitwarden"
smtp_host: "smtp.gmail.com"
smtp_port: "587"
smtp_ssl: "true"
smtp_username: "my_user@gmail.com"
smtp_password: "my_password"
admin_user_email: "bitwarden_admin@example.com"
cert_renewer_path: "/etc/systemd/system/bw-renewer.service"
environment_file: "{{ bitwarden_dir }}/bwdata/env/global.override.env"
bitwarden_cert_path: "/opt/bitwarden/bwdata/ssl/"
bitwarden_certificate_full_path: "{{ bitwarden_cert_path }}/{{ external_domain }}/certificate.crt"
bitwarden_key_full_path: "{{ bitwarden_cert_path }}/{{ external_domain }}/private.key"
reverse_proxy_servers:
  - 11.22.33.44
  - 55.66.77.88
