galaxy_info:
  role_name: cd_authentik
  namespace: irontooch
  author: IronTooch
  description: App_Description
  license: GPL-3.0-only
  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags: []

dependencies: 
  - '/mnt/c/Users/steve/Nextcloud/Development/Git/AnsibleCollections/irontooch/homelab/roles/su_docker'