galaxy_info:
  role_name: sy_vmsetup
  namespace: irontooch
  author: IronTooch
  description: A role specifically to manage any VM specific role items
  license: GPL-3.0-only
  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags: []

dependencies: []
