---
- name: Add MaaS repository
  ansible.builtin.apt_repository:
    repo: "{{ maas_repo }}"
    state: present
    update_cache: true
    validate_certs: true

- name: Install Dependency packages
  package:
    name:
      - acl
      - sudo
      - python3-pexpect
    state: present
