---
- name: Make ssh user if applicable
  ansible.builtin.set_fact:
    maas_ssh_id_options: "--ssh-import gh:{{ maas_github_id }}"
  when: maas_github_id is defined

- name: Make ssh user if not applicable
  ansible.builtin.set_fact:
    maas_ssh_id_options: ""
  when: maas_github_id is undefined

- name: Make command execution for MaaS Create Admin
  set_fact:
    mass_create_admin_cmd: >-
      maas
      createadmin
      --username {{ maas_admin_user }}
      --password {{ maas_admin_password }}
      --email {{ maas_admin_email }}
      {{ maas_ssh_id_options }}

- name: Create Admin User
  become: true
  ansible.builtin.shell:
    cmd: "{{ mass_create_admin_cmd }}"

  # ansible.builtin.expect:
  #   command: "{{ maas_make_user_command }}"
  #   chdir: "{{ my_app_dir }}"
  #   creates: "{{ my_app_install_artifact }}"
  #   responses:
  #     Password: "{{ maas_admin_password }}"
  #     Again: "{{ maas_admin_password }}"

# - name: Replace SMTP host
#   ansible.builtin.replace:
#     path: "{{ environment_file }}"
#     regexp: "globalSettings__mail__smtp__host=REPLACE"
#     replace: "globalSettings__mail__smtp__host={{ smtp_host }}"
#     owner: "{{ service_user }}"
#     group: "{{ service_user }}"
#     mode: '0700'

# - name: Own all of the bitwarden folder
#   ansible.builtin.file:
#     path: "{{ bitwarden_dir }}"
#     state: directory
#     recurse: true
#     owner: '{{ service_user }}'
#     group: '{{ service_user }}'

