---
# tasks file for pk_bounca
- name: Install BounCA Dependencies
  ansible.builtin.apt:
    name:  
      - gettext
      - nginx
      - python3
      - python3-dev
      - python3-setuptools
      - python-is-python3
      - uwsgi 
      - uwsgi-plugin-python3
      - virtualenv
      - python3-virtualenv
      - python3-pip
      - postgresql
      - postgresql-contrib
      - python3-psycopg2      # Needed for postgres modules
      - acl                   # Needed for become_user: postgres
    state: present
    update_cache: yes


- name: Create Postgres user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ bounca_dbuser }}"
    role_attr_flags: CREATEDB
  
- name: Create Postgres DB and grant to user
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ bounca_db }}"
    owner: "{{ bounca_dbuser }}"
    template: "template0"
    encoding: "UTF8"

- name: Create Logging Directory for BounCA
  ansible.builtin.file:
    path: /var/log/bounca
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Create Logging Directory for BounCA
  ansible.builtin.file:
    path: /etc/bounca
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Create Service Directory
  ansible.builtin.file:
    path: /var/www
    state: directory
    mode: '0755'
    owner: root
    group: root
  ignore_errors: true     # If directory already exists, nbd

- name: Get BounCA Release
  ansible.builtin.get_url:
    url: "{{ bounca_release }}"
    dest: "/tmp/bounca.tar.gz"
    force: "yes"

- name: Unzip BounCA Archive
  ansible.builtin.unarchive:
    src: "/tmp/bounca.tar.gz"
    dest: '/var/www'
    remote_src: yes


- name: Chown /var/www/bounca directory
  ansible.builtin.file:
    path: /var/www/bounca
    state: directory
    recurse: yes
    owner: 'www-data'
    group: 'www-data'



    
    
    



