---
- name: Make group for smallstep_user
  ansible.builtin.group:
    name: "{{ system_user }}"
    state: present
    system: true

- name: Make service user for smallstep_user
  ansible.builtin.user:
    name: "{{ system_user }}"
    state: present
    create_home: true
    groups: "{{ system_user }}"
    system: true
    shell: /bin/bash
