---
- name: Set variable for latest release tag without 'v'
  set_fact:
    latest_release_semver: "{{ latest_release.json.tag_name | replace('v','') }}"

- name: Download latest release for Step utility
  ansible.builtin.get_url:
    url: "https://github.com/smallstep/cli/releases/download/{{ latest_release.json.tag_name }}/step-cli_{{ latest_release_semver }}_amd64.deb"
    dest: "/tmp/smallstep_step.deb"
    force: "yes"
    owner: "smallstep_user"
    group: "smallstep_user"
    mode: "0770"
    validate_certs: "yes"

- name: Install Step application from debfile
  ansible.builtin.apt:
    deb: "/tmp/smallstep_step.deb"

- name: Add STEPPATH to /etc/profiles.d/
  ansible.builtin.copy:
    content: 'export STEPPATH=/etc/step-ca'
    dest: /etc/profile.d/steppath.sh
    force: true
    owner: "root"
    group: "root"
    mode: "0644"

- name: Add STEPPATH to /home/{{ system_user }}/.bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ system_user }}/.bashrc
    state: present
    line: 'export STEPPATH=/etc/step-ca'

- name: Add STEPPATH to /root/.bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    state: present
    line: 'export STEPPATH=/etc/step-ca'

- name: Make Step CA directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
  loop:
    - /etc/step-ca

- name: Make current version file (to save re-installs / support idempotence)
  copy:
    content: "{{ latest_release.json.tag_name }}"
    dest: "{{ installed_version_path }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: '0770'
