---


- name: Print certificate Name
  ansible.builtin.debug:
    msg: " {{ smallstep_certificate_name }} "
    verbosity: 0

- name: Print certificate filename
  ansible.builtin.debug:
    msg: " {{ smallstep_certificate_name }} "
    verbosity: 0

- name: Print key filename
  ansible.builtin.debug:
    msg: " {{ smallstep_key_filename }} "
    verbosity: 0

- name: Print subject names
  ansible.builtin.debug:
    msg: " {{ smallstep_step_smallstep_subject_names }} "
    verbosity: 0

- name: Make full Step Install command
  set_fact:
    cert_request_command: >-
      step ca certificate
      {{ smallstep_certificate_name }}
      {{ smallstep_certificate_filename }}
      {{ smallstep_key_filename }}
      {{ smallstep_step_smallstep_subject_names }}

- name: Print certificate request command
  ansible.builtin.debug:
    msg: "Cert Request Commmand: {{ cert_request_command }}"
    verbosity: 0

- name: Store a copy of the command to request the initial certs
  ansible.builtin.lineinfile:
    path: "/etc/step-ca/cert_request.sh"
    state: present
    line: "{{ cert_request_command }}"
    create: true
    owner: "{{ smallstep_system_user }}"
    group: "{{ smallstep_system_user }}"
    mode: "0700"

- name: Request certificate
  ansible.builtin.expect:
    command: "{{ cert_request_command }}"
    chdir: "/etc/step-ca"
    creates: "{{ smallstep_certificate_filename }}"
    responses:
      (?i)JWK: "\r"
      "Please enter the password to decrypt the provisioner key:": "{{ smallstep_provisioner_password }}"
  environment:
    STEPPATH: /etc/step-ca
