---
# tasks file for pk_stepcli
- name: Install Dependency packages
  package:
    name:
      - acl
    state: present

- name: Make group for smallstep_user
  ansible.builtin.group:
    name: "{{ smallstep_system_user }}"
    state: present
    system: true

- name: Make service user for smallstep_user
  ansible.builtin.user:
    name: "{{ smallstep_system_user }}"
    state: present
    create_home: true
    groups: "{{ smallstep_system_user }}"
    system: true
    shell: /bin/bash

- name: Get the latest tag from Github for Smallstep CA Step utility
  ansible.builtin.uri:
    url: https://api.github.com/repos/smallstep/cli/releases/latest
  register: latest_release

- name: Set variable for latest release tag without 'v'
  set_fact:
    latest_release_semver: "{{ latest_release.json.tag_name | replace('v','') }}"

- name: Download latest release for Step utility
  ansible.builtin.get_url:
    url: "https://github.com/smallstep/cli/releases/download/{{ latest_release.json.tag_name }}/step-cli_{{ latest_release_semver }}_amd64.deb"
    dest: "/tmp/smallstep_step.deb"
    force: "yes"
    owner: "smallstep_user"
    group: "smallstep_user"
    mode: "0770"
    validate_certs: "yes"

- name: Install Step application from debfile
  ansible.builtin.apt:
    deb: "/tmp/smallstep_step.deb"