---
# tasks file for pk_stepcli
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "01_install_dependencies.yml"

- name: Add Service User
  ansible.builtin.include_tasks:
    file: "02_create_serviceuser.yml"

- name: Get the latest tag from Github for Smallstep CA Step utility
  ansible.builtin.uri:
    url: https://api.github.com/repos/smallstep/cli/releases/latest
  register: latest_release
  tags: install_smallstep

- name: Get version from file
  ansible.builtin.shell:
    cmd: "test -f \"{{ installed_version_path }}\" && cat {{ installed_version_path }}"
  register: installed_version
  failed_when: false
  changed_when: false
  tags: install_smallstep

- name: Install Step CLI if needed
  ansible.builtin.include_tasks:
    file: "03_install_stepcli.yml"
  when: (installed_version.stdout != latest_release.json.tag_name)
  tags: install_smallstep

- name: Check to see if Root CA is installed
  ansible.builtin.stat:
    path: "/etc/step-ca/certs/root_ca.crt"
  register: root_ca_installed
  tags: install_rootca

- name: Install Root Certificate
  ansible.builtin.include_tasks:
    file: "04_install_rootca.yml"
  when: not root_ca_installed.stat.exists
  tags: install_rootca

# step ca certificate svc.example.com svc.crt svc.key
- name: Check to see if Leaf Cert is created
  ansible.builtin.stat:
    path: "/etc/step-ca/certs/{{ certificate_filename }}"
  register: leaf_cert_exists
  tags: install_leafcert

- name: Get Leaf Certificate
  ansible.builtin.include_tasks:
    file: "05_make_initialcertificates.yml"
  when: not leaf_cert_exists.stat.exists
  tags: install_leafcert

- name: Check to see if Services are Deployed
  ansible.builtin.stat:
    path: "/etc/systemd/system/cert-renewer@.timer"
  register: services_deployed
  tags: install_services

- name: Get Leaf Certificate
  ansible.builtin.include_tasks:
    file: "06_install_renewalservices.yml"
  when: not services_deployed.stat.exists
  tags: install_services

# Switch on Nginx / Tomcat / Apache / Others
# https://smallstep.com/docs/step-ca/certificate-authority-server-production#automated-renewal

- name: Install certificates into Nginx and start renewal configuration
  ansible.builtin.include_tasks:
    file: "07a_nginx_certs.yml"
  when: dependent_service == "nginx"

- name: Install certificates into Proxmox and start renewal configuration
  ansible.builtin.include_tasks:
    file: "07b_proxmox_certs.yml"
  when: dependent_service == "proxmox"